### ISSUE TITLE
JSONDecodeError

### ISSUE THREAD

**Issue by Soham-Das-afk** [serv0id/skipera#2]
getting some error...

2024-03-09 00:09:42.831 | ERROR    | __main__:<module>:89 - An error has been caught in function '<module>', process 'MainProcess' (20184), thread 'MainThread' (12536):
Traceback (most recent call last):

  File "C:\Users\soham\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\requests\models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
           │           │     │    │       └ {}
           │           │     │    └ <property object at 0x0000022C122DEA20>
           │           │     └ <Response [200]>
           │           └ <function loads at 0x0000022C11E36840>
           └ <module 'json' from 'C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.12_3.12.752.0_x64__qbz5n2kfra8p0\\Lib\...
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.752.0_x64__qbz5n2kfra8p0\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           │                │      └ '<!DOCTYPE html><html xmlns:fb="http://ogp.me/ns/fb#" itemtype="http://schema.org" lang="en" dir="ltr"><head><link rel="preco...
           │                └ <function JSONDecoder.decode at 0x0000022C11E36160>
           └ <json.decoder.JSONDecoder object at 0x0000022C11DF37A0>
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.752.0_x64__qbz5n2kfra8p0\Lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               │    │          │      │  └ '<!DOCTYPE html><html xmlns:fb="http://ogp.me/ns/fb#" itemtype="http://schema.org" lang="en" dir="ltr"><head><link rel="preco...
               │    │          │      └ <built-in method match of re.Pattern object at 0x0000022C11E2C6C0>
               │    │          └ '<!DOCTYPE html><html xmlns:fb="http://ogp.me/ns/fb#" itemtype="http://schema.org" lang="en" dir="ltr"><head><link rel="preco...
               │    └ <function JSONDecoder.raw_decode at 0x0000022C11E36200>
               └ <json.decoder.JSONDecoder object at 0x0000022C11DF37A0>
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.752.0_x64__qbz5n2kfra8p0\Lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
          │                                  └ '<!DOCTYPE html><html xmlns:fb="http://ogp.me/ns/fb#" itemtype="http://schema.org" lang="en" dir="ltr"><head><link rel="preco...
          └ <class 'json.decoder.JSONDecodeError'>

json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

> File "C:\Users\soham\OneDrive\Desktop\New folder\main.py", line 89, in <module>
    main()
    └ <function main at 0x0000022C128040E0>

  File "C:\Users\soham\OneDrive\Desktop\New folder\main.py", line 85, in main
    skipera = Skipera(sys.argv[1])
              │       │   └ ['main.py', 'os-power-user']
              │       └ <module 'sys' (built-in)>
              └ <class '__main__.Skipera'>

  File "C:\Users\soham\OneDrive\Desktop\New folder\main.py", line 15, in __init__
    if self.get_userid() == 0:
       │    └ <function Skipera.get_userid at 0x0000022C127FEE80>
       └ <__main__.Skipera object at 0x0000022C1275D190>

  File "C:\Users\soham\OneDrive\Desktop\New folder\main.py", line 30, in get_userid
    r = self.session.get(self.base_url + "adminUserPermissions.v1?q=my").json()
        │    │       │   │    └ 'https://www.coursera.org/learn/os-power-user/home/module/2'
        │    │       │   └ <__main__.Skipera object at 0x0000022C1275D190>
        │    │       └ <function Session.get at 0x0000022C122F2700>
        │    └ <requests.sessions.Session object at 0x0000022C1275D0D0>
        └ <__main__.Skipera object at 0x0000022C1275D190>

  File "C:\Users\soham\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\requests\models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
          └ <class 'requests.exceptions.JSONDecodeError'>

requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by serv0id** [comment]
Are you setting the cookies properly as described in https://github.com/serv0id/skipera/issues/1 ?

**Comment by Soham-Das-afk** [comment]
Yes

**Comment by astravaganza** [comment]
Could you please change line 30 to 
`r = self.session.get(self.base_url + "adminUserPermissions.v1?q=my")` 
and add
`print(r)` 
just after line 30 and paste the output here?
